### ISSUE TITLE
NameError: name 'profile' is not defined: when try to  "Plot memory usage as a function of time"

### ISSUE THREAD

**Issue by scotthuang1989** [pythonprofilers/memory_profiler#181] opened 2018-01-02 13:11 UTC
version: 0.50.0
In the official documentation. there is a link to this [blog](http://fa.bianp.net/blog/2014/plot-memory-usage-as-a-function-of-time/). but when I try to run the exactly code in this post. I get this error:

> Traceback (most recent call last):
> 
>   File "test.py", line 3, in <module>
>     @profile
> NameError: name 'profile' is not defined

this is very strange, because there is the quotes from official :

> Warning
> 
> If your Python file imports the memory profiler from memory_profiler import profile these timestamps will not be recorded. Comment out the import, leave your functions decorated, and re-run.

So if I want to have the per-function memory usage plot, I need comment out  `from memory_profiler import profile`, but when I comment out it, there is a error.

**Comment by scotthuang1989** [comment] 2018-01-03 00:01
I also ask the problem at stackoverflow, I got a [workaround](https://stackoverflow.com/questions/48061659/memory-profiler-how-to-plot-per-function-memory-usage/48062429#48062429), maybe it can help you guys figure out what's going on.

**Comment by fabianp** [comment] 2018-01-06 19:34
Thanks for the report @scotthuang1989 , this is hopefully fixed in   6478e66

**Closed by fabianp** 2018-01-06 19:34 UTC

**Comment by mujina93** [comment] 2020-08-26 12:09
Got a similar problem with python 3.7 and memory-profiler 0.57.0

The solution that worked for me is the one from the [workaround](https://stackoverflow.com/questions/48061659/memory-profiler-how-to-plot-per-function-memory-usage/48062429#48062429) linked above. 

I.e. running with

```python
mprof run --python python path/to/script.py
```

**Comment by fabianp** [comment] 2020-08-30 22:43
Hi @mujina93 : it would be great if you can provide a minimal example for this, as I can't reproduce this bug. Thanks!
