### ISSUE TITLE
Unicode files not handled correctly in Python 3 

### ISSUE THREAD

**Issue by swartchris8** [pythonprofilers/memory_profiler#244] opened 2019-09-02 14:02 UTC
The issue raised in https://github.com/pythonprofilers/memory_profiler/issues/113 for Python 2 is still not handled in Python 3.

To reproduce:

`test_example.py`

```
# -*- coding: utf-8  -*-
from memory_profiler import profile
@profile
def test_unicode(txt):
    # test when unicode is present
    txt = txt.replace (u"ی", u"ي") #Arabic Yah = ي
    return txt
print(test_unicode(u"ایست"))
```

```
python3 -m memory_profiler test_example.py
```

When running this I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/venv3/lib/python3.5/site-packages/memory_profiler.py", line 1227, in <module>
    exec_with_profiler(script_filename, prof, args.backend, script_args)
  File "/opt/venv3/lib/python3.5/site-packages/memory_profiler.py", line 1128, in exec_with_profiler
    exec(compile(f.read(), filename, 'exec'), ns, ns)
  File "/opt/venv3/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdb in position 153: ordinal not in range(128
```

I think a potential solution could be using io.open for Python 2 and 3 compatibility https://python-future.org/compatible_idioms.html#file-io-with-open though I am not sure how you envision Python 2 and 3 compatibility.

**Comment by fabianp** [comment] 2019-09-02 14:21
Pull requests welcome.

**Comment by swartchris8** [comment] 2019-09-03 09:12
Okay created a PR, hope it gets accepted.

**Comment by swartchris8** [comment] 2019-09-03 10:29
Okay created a PR, hope it gets accepted.

**Comment by abubelinha** [comment] 2021-10-01 08:26
@swartchris8 sorry about this question but I am not a Python or github expert. 
Is there a way I can see your PR and try to manually patch my installed memory_profiler scripts?

Although my error message is not identical, I believe I could be having a similar issue (Python 3.4, WindowsXP, psutil-3.4.2, memory-profiler-0.58.0):

```
C:\python34\python -m memory_profiler createdoc.py
Traceback (most recent call last):
  File "c:\python34\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python34\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\python34\lib\site-packages\memory_profiler.py", line 1303, in <module>
    exec_with_profiler(script_filename, prof, args.backend, script_args)
  File "c:\python34\lib\site-packages\memory_profiler.py", line 1204, in exec_with_profiler
    exec(compile(f.read(), filename, 'exec'), ns, ns)
  File "c:\python34\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4235: character maps to <undefined>
```

Unfortunately I cannot provide a sample reproducible code, because I can't tell which line in my script (createdoc.py)  should I look at. There are many other functions being imported and I don't know what else I could provide:

createdoc.py

```Python
# a lot of code before

@profile
def mytestfunction(...): # the_function_I_try_to_test_memory_usage
   from docx import Document
   from docx.shared import Inches,Cm,Pt
   from myownfunctions import PyGdrive, myhash, mypickfile, mypyversion
   # a lot of code here

# a lot of code after, and somewhere mytestfunction() is called
```

**Comment by abubelinha** [comment] 2021-10-01 08:49
Nevermind, I figured it out:

I just edited this line in `memory_profiler.py` function `exec_with_profiler`:
```Python
        with open(filename) as f:
```
and changed it to:
```Python
        with open(filename, 'rb') as f:
```

And YES, it solved my issue as well.
I can't understand why such an easy issue is not solved yet.

**Comment by fabianp** [comment] 2022-02-09 20:42
finally merged

**Closed by fabianp** 2022-02-09 20:42 UTC
